import { stringify } from "yaml";
import type { DevexConfig } from "../../config/devex-config.schema.js";
import { buildGovernanceJob } from "../jobs/governance-job.js";
import { buildSmallTestsJob } from "../jobs/small-tests-job.js";
import { buildCdkSynthJob } from "../jobs/cdk-synth-job.js";
import type { GithubJob, GithubWorkflow } from "../types.js";

// ---------------------------------------------------------------------------
// PR workflow generator
//
// createPrWorkflow(config) → GithubWorkflow
//
// Produces a workflow object for the PR pipeline of a service whose
// configuration lives in devex.yaml. Validates code quality and
// infrastructure synthesis before a PR can be merged — without deploying.
//
// Job dependency graph:
//
//   governance
//       │
//   small-tests
//       │
//   cdk-synth  ← only when infraFramework === "aws-cdk-typescript"
//
// Deployments and DORA telemetry are handled by the Main workflow, which
// runs after the PR merges to the main branch.
// ---------------------------------------------------------------------------

export interface PrWorkflowOptions {
  /** GitHub Actions runner label. Defaults to "ubuntu-latest". */
  runsOn?: string;
}

/**
 * Creates a PR workflow object for the given service configuration.
 *
 * The workflow triggers on `pull_request` events and runs:
 * governance → small tests → CDK synth (if applicable).
 *
 * @example
 * import { loadConfig, createPrWorkflow, renderWorkflowYaml } from "@loanpro/devex-workflow-framework";
 * const config = await loadConfig();
 * const workflow = createPrWorkflow(config);
 * const yaml = renderWorkflowYaml(workflow);
 * writeFileSync(".github/workflows/pr.yml", yaml);
 */
export function createPrWorkflow(
  config: DevexConfig,
  options: PrWorkflowOptions = {}
): GithubWorkflow {
  const runsOn = options.runsOn ?? "ubuntu-latest";
  const hasCdk = config.runtime.infraFramework === "aws-cdk-typescript";

  const jobs: Record<string, GithubJob> = {};

  // -------------------------------------------------------------------------
  // 1. Governance — no dependencies, gates everything downstream
  // -------------------------------------------------------------------------
  jobs["governance"] = buildGovernanceJob(config, { runsOn });

  // -------------------------------------------------------------------------
  // 2. Small tests — needs governance
  // -------------------------------------------------------------------------
  jobs["small-tests"] = buildSmallTestsJob(config, {
    runsOn,
    needs: ["governance"],
  });

  // -------------------------------------------------------------------------
  // 3. CDK synth — needs small-tests (only for CDK services)
  // -------------------------------------------------------------------------
  if (hasCdk) {
    jobs["cdk-synth"] = buildCdkSynthJob(config, {
      runsOn,
      needs: ["small-tests"],
    });
  }

  return {
    name: "PR Pipeline",
    on: {
      workflow_dispatch: {},
      pull_request: {
        types: [
          "opened",
          "synchronize",
          "reopened",
          "ready_for_review",
          "edited",
        ],
      },
    },
    permissions: {
      contents: "read",
      "pull-requests": "write",
      checks: "write",
    },
    jobs,
  };
}

/**
 * Serialises a GithubWorkflow object to a YAML string.
 *
 * Prepends a machine-generated header so service teams know not to edit the
 * file manually and can identify the correct regeneration command.
 *
 * Multi-line `run:` strings (e.g. inline Node.js scripts) are rendered as
 * YAML literal block scalars (`|`) automatically by the yaml library.
 */
export function renderWorkflowYaml(workflow: GithubWorkflow): string {
  const header = [
    "# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json",
    "#",
    "# This file was generated by @loanpro/devex-workflow-framework.",
    "# Do not edit manually — regenerate with:",
    "#   node scripts/generate-workflows.mjs",
    "",
    "",
  ].join("\n");

  return header + stringify(workflow, { lineWidth: 0 });
}
